version: '2.3'

services:
  adherent_dev_joystick_gpu:
    image: "ghcr.io/paolo-viceconte/adherent-docker-dev-gpu"
    container_name: "adherent_dev_joystick_gpu"
    command: "bash"
    init: true
    environment:
      - YARP_NAME_SPACE=/evelyd
    stdin_open: true
    tty: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    devices:
      - "/dev/input/js0:/dev/input/js0"
    dns:
      - 8.8.8.8

 
devenv:
  version: '1.0'
  adherent_dev_joystick_gpu:
    user: "evelyd"
    project_dir: "$HOME/git"
    resources:
      directories:
        - "$HOME/.dockerdot/atom:$HOME/.atom"
        - "$HOME/.dockerdot/config/atom:$HOME/.config/Atom"
        - "$HOME/.dockerdot/ccache:$HOME/.ccache"
        - "$HOME/.dockerdot/config/qtcreator:$HOME/.config/QtProject"
        - "$HOME/.dockerdot/config/JetBrains:$HOME/.config/JetBrains"
        - "$HOME/.dockerdot/cache:$HOME/.cache"
      files:
        - "$HOME/.dockerdot/z:$HOME/.z"
        - "$HOME/.dockerdot/bash_history:$HOME/.bash_history"
    gpu: "nvidia"
    x11: "xauth"
    gdb: true
    git:
      username: "Evelyn D'Elia"
      email: "17877131+evelyd@users.noreply.github.com"
